### ISSUE TITLE
Assignment to Objective-C's isa deprecated in favor of object_setClass()

### ISSUE THREAD

**Issue by wongzigii** [johnezang/JSONKit#157]
Error happens on  Line 680 and Line 932.
Anyone know how to fix it, please?

**Comment by abhibeckert** [comment]
Personally I'm "fixing" it by switching to `NSJSONSerialization`.

A year ago, I ran into problems with JSONKit being unable to compile for 64 bit. Forcing a 32 bit compile solved it but that was only ever a temporary solution. Soon Apple will require code compiled for 64 bit.

Since JSONKit is not keeping up with changes in iOS, it is time for everyone to stop using it.

**Comment by wongzigii** [comment]
@abhibeckert  anyway,thanks.
