### ISSUE TITLE
removeObjectsForKeys doesn't properly remove objects

### ISSUE THREAD

**Issue by jfmorin** [johnezang/JSONKit#17]
Hi,

There is a problem with the NSMutableDictionary returned by mutableObjectFromJSONString. A call to removeObjectsForKeys will remove the objects but not the keys. So we end up with nil objects. I also noticed side effects on other dictionary values that should not be affected.

Should it be overridden in the JKDictionary class like removeObjectForKey is?

Thanks,
JF

**Comment by johnezang** [comment]
Can you provide the JSON and some example code the demonstrates the problem?

From your description, it's not clear what the problem is.  When you say "A call to removeObjectsForKeys will remove the objects but not the keys. So we end up with nil objects.", this is the expected behavior- when a `NSDictionary` does not contain a key, `-objectForKey:` will return `nil` (aka `NULL`).

**Comment by jfmorin** [comment]
Instead of removing the key/value pair as expected, the key remains in the mutable dictionary but the value is replaced by a null value. If I print the resulting object I can see: "myKey"=(null).

**Comment by johnezang** [comment]
The behavior you describe is the expected behavior.  The key does not "remain" in the dictionary, any key that does not exist in the dictionary returns `NULL` (aka `nil`).  There are a number of internal checks in the form of `NSCParameterAssert` that ensure that every key in the dictionary contains a non-`NULL` object associated with it.  If you did not compile JSONKit with `NS_BLOCK_ASSERTIONS`, these checks are enabled, and would have caused an exception, which would have been logged to the console.

I suggest you try creating a `NSMutableDictionary` with a number of keys/objects.  Remove one of the keys, and see if the `NSMutableDictionary` has the same behavior for the removed key.

**Comment by omarkilani** [comment]
Hey John,

I think what the OP is seeing is this (with JSONKit 2e6ccf4ecc28db1e7c511546f269233d96c87f4c):

Code:

```
  NSMutableDictionary *jkDict = [@"{\"a\":\"1\",\"b\":\"2\",\"c\":\"3\"}" mutableObjectFromJSONString];
  NSLog(@"jkDict = %@", jkDict);

  NSMutableDictionary *objcDict = [NSMutableDictionary dictionaryWithObjectsAndKeys:@"1", @"a", @"2", @"b", @"3", @"c", nil];
  NSLog(@"objcDict = %@", objcDict);

  [jkDict removeObjectForKey:@"b"];
  [objcDict removeObjectForKey:@"b"];

  NSLog(@"jkDict = %@", jkDict);
  NSLog(@"objcDict = %@", objcDict);
```

Output:

```
2011-04-22 14:46:05.354 main[90231:903] jkDict = {
    a = 1;
    b = 2;
    c = 3;
}
2011-04-22 14:46:05.357 main[90231:903] objcDict = {
    a = 1;
    b = 2;
    c = 3;
}
2011-04-22 14:46:05.358 main[90231:903] jkDict = {
    a = 1;
    c = (null);
}
2011-04-22 14:46:05.358 main[90231:903] objcDict = {
    a = 1;
    c = 3;
}
```

**Comment by omarkilani** [comment]
Hey John,

I've tracked this down to the fix which fixed issue #8 :)

https://github.com/johnezang/JSONKit/commit/524b9d78d3a0e68d3376abea039b63957ed71e7e

Specifically this line:

https://github.com/johnezang/JSONKit/commit/524b9d78d3a0e68d3376abea039b63957ed71e7e#L0R1014

This comment:

 // If the key was in the table, we would have found it by now.

Is incorrect if removeObjectForKey was used (like my example above).

dictionary->entry looks like this with the example:

[0] = {keyHash = 1062, key = @"a", object = "1"}
[1] = {keyHash = 0, key = NULL, object = NULL}
[2] = {keyHash = 1068, key = @"c", object = "3"}

So the loop terminates with NULL due to [1], but we need to keep going to find [2].

**Comment by johnezang** [comment]
@omarkilani, the line you mentioned in your comment is one half of the problem.  The real problem is in the removal logic- it (should have) "re-added" the items following the removed entry so that linear probe hash collisions didn't result in a `NULL` gap in the middle of the linear probe hash collision.

Your example code was very useful- it happened to create a dictionary with 3 items with a capacity of 3 items, and `a`, `b`, and `c` all just happened to be ≡ 0 mod 3.  Sort of a "perfect storm" to exercise this bug.

I checked in a bug fix for this issue (used the new github issues feature to close this issue automagically with "Closes #17").

**Comment by jfmorin** [comment]
Thanks for the help reproducing the problem and fixing it.
Good job!

**Comment by omarkilani** [comment]
@johnezang, Thanks for the fix. Yeah, the real problem became obvious once I started delving in a bit more. I seem to get pretty lucky with just the right dictionaries to trigger things. :)

Thanks again.
