### ISSUE TITLE
Why must the caller retain the new object for JKArray methods

### ISSUE THREAD

**Issue by stigi** [johnezang/JSONKit#18]
I browsed through your code and wondered why exactly the caller is responsible to retain the object that is going to be inserted into the array via _JKArray methods.
You're using CFRelease and -autorelease to manage retain counts in those methods, but no CFRetain or -retain. I'm sure there's a reason for that, but I could not figure out what it is.

Please enlighten me :)

best,
Ullrich

**Comment by johnezang** [comment]
Some of this is covered in `CHANGELOG.md`, but the short explanation is that this implements a "transfer of ownership" memory management policy.

The normal object ownership flow for collections usually has the collection `CFRetain` an object when it is added to the collection via a `AddToCollection` type of call.  Once added to the collection, whatever added it to the collection must call `CFRelease` in order to balance things out.

With a "transfer of ownership" type of policy, the collection omits the `CFRetain`, and the whatever is adding the object to the collection omits the `CFRelease`.  The retain counts balance out to be the same, with two fewer retain / release calls.

Since the number of objects that JSONKit creates tends to be a lot, eliminating these calls actually improves performance.  Part of the reason why it results in a performance increase is because the retain and release calls (for the types of objects JSONKit creates) are implemented with atomic CPU primitives, which have a tendency to be "very expensive" to execute.
