### ISSUE TITLE
Learning Question

### ISSUE THREAD

**Issue by jasongregori** [johnezang/JSONKit#41]
Hi John,

I'm just trying to learn and understand your marvelous code :). I saw this and was confused by it. If you have a second I thought you might shed some light.

``` objc
#if       defined (__GNUC__) && (__GNUC__ >= 4)
#define JK_ATTRIBUTES(attr, ...)        __attribute__((attr, ##__VA_ARGS__))
#define JK_EXPECTED(cond, expect)       __builtin_expect((long)(cond), (expect))
#define JK_EXPECT_T(cond)               JK_EXPECTED(cond, 1U)
#define JK_EXPECT_F(cond)               JK_EXPECTED(cond, 0U)
#define JK_PREFETCH(ptr)                __builtin_prefetch(ptr)
#else  // defined (__GNUC__) && (__GNUC__ >= 4) 
#define JK_ATTRIBUTES(attr, ...)
#define JK_EXPECTED(cond, expect)       (cond)
#define JK_EXPECT_T(cond)               (cond)
#define JK_EXPECT_F(cond)               (cond)
#define JK_PREFETCH(ptr)
#endif // defined (__GNUC__) && (__GNUC__ >= 4) 
```

`JK_EXPECT_T` looks like it's supposed to return `true` if the condition is `true` and `JK_EXPECT_F` looks like it's supposed to return `true` if the condition is `false`. But in the `#else` section they both return the same thing. Is this a bug or something that makes sense when `defined (__GNUC__) && (__GNUC__ >= 4)` is `false`?

**Comment by johnezang** [comment]
The `JK_EXPECT_T` and `JK_EXPECT_F` are preprocessor macros that are used to abstract a feature often provided by optimizing compilers.  Specifically, it allows you to give the optimizer a hint as to which condition is most likely to occur: the `true` condition, or the `false` condition.  The `__builtin_expect()` "function" has the following behavior:
- `__builtin_expect(x, y)`, where `x` is `0`, returns a result of `0`.
- `__builtin_expect(x, y)`, where `x` is `!= 0`, returns a result of `1`.

In either case of `x`, `y` does not change the result that is "returned".  In other words, `__builtin_expect()` effectively "does nothing".

However, internally the optimizer makes a note of the value of `y`.  When a modern CPU encounters a conditional branch, it may not have all the information needed at that point in time to know exactly which branch it should follow- the `true` or `false` side (this is due to pipelining, cache and memory latencies, etc).  Modern CPU's will typically being to speculatively execute one of the paths, and if it later determines that it picked the wrong one, it requires an expensive flush of the CPU state to undo all the speculatively execute instructions, and then restart instruction execution on the correct path.

By using `__builtin_expect()`, you can help the CPU pick the correct path to follow "most of the time", which translates in to better performance.

**Comment by jasongregori** [comment]
Thanks John

**Comment by steipete** [comment]
If i get this right, clang/llvm doesn't use these hints?
