### ISSUE TITLE
Garbace Collector Unsupported

### ISSUE THREAD

**Issue by loretoparisi** [johnezang/JSONKit#44]
I'm using JSONKit in a Cocoa application and I started using the gc and realized that JSONKit is not supporting gc.
Is there any workaround or a beta version to enable it?

thanks

**Comment by schubter** [comment]
> JSONKit is not designed to be used with the Mac OS X Garbage Collection. The behavior of JSONKit when compiled with  -fobjc-gc is undefined. It is extremely unlikely that Mac OS X Garbage Collection will ever be supported.

from the readme

**Comment by loretoparisi** [comment]
So since my Cocoa app needs GC I have to ways...further testing the JSONKit with -fobjc-gc (A) or - B - switch to another json parser.
Currently I decided to implement solution A, and our testing is going good until now.

**Comment by johnezang** [comment]
As noted by @schubter, JSONKit does not support Mac OS X Garbage Collection.  It is explicitly stated in the documentation, and there are various preprocessor statements in JSONKit so that it will fail to compile if you try to compile it with something like `-fobjc-gc`.

You **MUST NOT** use JSONKit in a Garbage Collected environment.

The fact that "it seems to work" **_does not**_ mean that it works **_correctly**_.  In fact, this is precisely the reason why I no longer program using Cocoa's Garbage Collection: There is simply no way to determine if a Cocoa Garbage Collected program is working correctly because your code is correct, or if you've got a serious GC related bug and have just been lucky because you haven't tickled the right set of circumstances that would cause the collector to collect an object that happens to be in use.

There are very specific and complicated rules you need to follow when using Garbage Collection, just as there are when using `retain`/`release`.  JSONKit _was not_ coded to respect those GC rules.  This means that if it's working for you, it's because you've just been lucky.

**Comment by loretoparisi** [comment]
So, it's a good reason to switch back GC to "Unsopported". 
Thanks a lot.
