### ISSUE TITLE
NSDate support

### ISSUE THREAD

**Issue by ceh329** [johnezang/JSONKit#52]
Hello,
Can you please add support for NSDate type. I would think you could just map NSDate/CFDate to a String.

Thanks!

**Comment by johnezang** [comment]
I don't necessarily disagree with you, but I have to balance a number of different priorities.  Therefore, I have, so far, been of the opinion that `NSDate` support should not be brought in to the JSONKit core.

_However_, this is an obviously useful feature.  Therefore, instead of trying to create one off exceptions, I have thought about what the best primitive(s) would be so that users could, at least in some sense, "extend" JSONKit to fit their needs.

To that end, if you pull down the **master** branch and take a look at `CHANGELOG.md`, you will find some example code that you can cut and paste that does exactly what you want... at least in terms of turning `NSDate` objects in to JSON strings.  The reverse (turning JSON strings containing "date" information in to `NSDate` objects) is not nearly as straight forward, and I have no immediate solution to offer, other than it would require you to enumerate the contents of the returned collection object and manually convert the JSON strings in to `NSDate` objects at the appropriate places.

**Comment by ghost** [comment]
if you store them the same way than a plist e.g iso GMT (the secret never include the time shift always store GMT), then you try to match the mask using posix regexp, thus that's easy to create the date from string you have the formatter @"yyyy-MM-dd'T'kk:mm:ss'Z'" and server side the same what so ever php ruby perl 

``` c
#include <sys/types.h>
#include <regex.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char * argv[])
{
    regex_t regex;
    int ret;
    char buffer[200];
// optional tests we should not, just an example
    ret = regcomp(&regex, "^([0-9][0-9][0-9][0-9])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([0-1]?[0-9]|2[0-3]):([0-5]?[0-9]):([0-5]?[0-9])Z$", REG_EXTENDED|REG_NOSUB|REG_ICASE);
    if (ret) { fprintf(stderr, "could not compile\n"); exit(1); }
// now it needs to be benchmarked but quite sure 
// that's 100 times faster than your obj-c tweaking
    ret = regexec(&regex, "2012-05-21T23:51:13Z", 0, NULL, 0);
    if (!ret) {
        puts("match");
    } else if (ret == REG_NOMATCH) {
        puts("no match");
    } else {
        regerror(ret, &regex, buffer, sizeof(buffer));
        fprintf(stderr, "error: %s\n", buffer);
        exit(1);
    }
    regfree(&regex);
    return 0;
}
```
