### ISSUE TITLE
Error decoding JSonString

### ISSUE THREAD

**Issue by pepobit** [johnezang/JSONKit#64]
Hello,

I have this JSON string:

{"data": 
         {77: {"number": 0, "photo": ""},
         {78: {"number": 3, "photo": ""},
         ...
};

My code is:

  JSONDecoder *jsDecoder = [JSONDecoder decoder];
  NSArray *arrayElements = [jsDecoder objectWithData:responseDara error:&msgError];

To decode gives the error "Error Domain = JKErrorDomain Code = 1 " Expected to "STRING" or a '}', not '77' "
What is wrong?

**Comment by djbe** [comment]
That's because your json is incorrect. It could be corrected to, for example:

```
{
    "data": {
        "77": {
            "number": 0,
            "photo": ""
        },
        "78": {
            "number": 3,
            "photo": ""
        }
    }
}
```

**Comment by johnezang** [comment]
The problem is that the JSON you are trying to parse is not well formed.  JSONKit is designed to parse JSON as it is defined by the [JSON RFC 4627](http://tools.ietf.org/html/rfc4627).

You can use something like [JSONLint](http://jsonlint.com/) to quickly check if the JSON you are having problems with is, in fact, really JSON, and not some Javascript trying to pass itself off as JSON.
