### ISSUE TITLE
problem while reading weather data

### ISSUE THREAD

**Issue by a-v-ebrahimi** [johnezang/JSONKit#78]
Hi

I need to read following JSON string :

{
data: {
current_condition: [
{
cloudcover: "0",
humidity: "58",
observation_time: "01:51 AM",
precipMM: "0.0",
pressure: "1016",
temp_C: "11",
temp_F: "52",
visibility: "10",
weatherCode: "113",
weatherDesc: [
{
value: "Sunny"
}
],
weatherIconUrl: [
{
value: "http://www.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
}
],
winddir16Point: "N",
winddirDegree: "0",
windspeedKmph: "0",
windspeedMiles: "0"
}....

how can I read **weatherIconUrl**?
NSDictionary *items = [MyRowJson objectFromJSONStringWithParseOptions:true];
                NSDictionary  *response = [items objectForKey:@"data"];
                NSDictionary  *response2 = [response objectForKey:@"current_condition"];
                NSDictionary  *response3 = [response2 objectForKey:@"weatherIconUrl"];

the line for **response3** crashes.

thank you

**Comment by PaulCapestany** [comment]
When you try to access `response3` the app crashes for you because `current_condition` is an **NSArray**, _not_ an **NSDictionary**. 

The JSON format specifies that array items are placed within brackets `[…]`, whereas dictionaries are placed within curly braces `{…}`.

So instead of: 

```
NSDictionary *response = [items objectForKey:@"data"];
NSDictionary *response2 = [response objectForKey:@"current_condition"];
NSDictionary *response3 = [response2 objectForKey:@"weatherIconUrl"];
```

Try this:

```
NSDictionary *originalResponse = [items objectForKey:@"data"];
NSArray *currentConditionsArray = [originalResponse objectForKey:@"current_condition"];
NSDictionary *aCurrentConditionsDictionary = [currentConditionsArray objectAtIndex:0];
NSArray *potentialWeatherIconURLs = [aCurrentConditionsDictionary objectForKey:@"weatherIconUrl"];
NSDictionary *dictionaryOfWeatherIconURLValues = [potentialWeatherIconURLs objectAtIndex:0];
NSString *theActualValueOfTheWeatherIconURL = [dictionaryOfWeatherIconURLValues objectForKey:@"value"];
```

So if you **NSLog()** `theActualValueOfTheWeatherIconURL`, you should get the string that you want:

```
NSLog(@"theActualValueOfTheWeatherIconURL = %@", theActualValueOfTheWeatherIconURL);
// should output "http://www.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png"
```

You may also want to try using some JSON formatters to better visualize the data, it's easy to get lost between all the braces and brackets.  Hopefully that helps you!

**Comment by a-v-ebrahimi** [comment]
Thank you very much Paul

It fixed my problem, since I have roots in Java and C#, i have difficulties in understanding Objective C!

Best regards
