### ISSUE TITLE
isa is deprecated

### ISSUE THREAD

**Issue by trawor** [johnezang/JSONKit#79]
I got lots of warning like this: `/PATH/JSONKit.m:2602:11: 
Direct access to objective-c's isa is deprecated in favor of object_setClass() and object_getClass()`

My Xcode is up to 4.4 DP4

**Comment by christo16** [comment]
Same issue here, happened after upgrading.

**Comment by shannoga** [comment]
Same issue  on 4.4 DP5

**Comment by oneredstar** [comment]
This can be fixed by replacing

```
object->isa
```

with

```
object_getClass(object)
```

You will also need to replace

```
keyObject->isa
```

with

```
object_getClass(keyObject)
```

and

```
(id)keys[idx]->isa
```

with

```
object_getClass((id)keys[idx])
```

**Comment by shannoga** [comment]
Thanks, When trying to replace I noticed this note on the file:
<code>
  Why not just use `object_getClass()`?  Because `object->isa` reduces to (typically) a _single_ instruction.  Calling `object_getClass()` requires
  //     that the compiler potentially spill registers, establish a function call frame / environment, and finally execute a "jump subroutine" instruction.
  //     Then, the called subroutine must spend half a dozen instructions in its prolog, however many instructions doing whatever it does, then half a dozen
  //     instructions in its prolog.  One instruction compared to dozens, maybe a hundred instructions.
  //  
  //     Yes, that's one to two orders of magnitude difference.  Which is compelling in its own right.  When going for performance, you're often happy with
  //     gains in the two to three percent range.
</code>

Is it still O.K to change that ?
Thanks

**Comment by oneredstar** [comment]
You can still keep using **object->isa**, but eventually that will be dropped as it is deprecated, unless there's a faster way to do the same thing without using **object_getClass()**, it is the next best solution for now.

If you still wish to use **object->isa**, you can suppress the warnings.

**Comment by MSch** [comment]
Regarding the `object->isa` deprecation, once thing I'm not sure of:

Does `isa` return the `NSNumber` for the new `NSNumber`s that are implemented via tagged pointers? (AFAIK that's the reason `isa` is deprecated)

**Comment by drekka** [comment]
I was researching this issue and found https://gist.github.com/2171491 which suggested to me that object_getClass() is no longer slower that isa.

**Comment by antonysastre** [comment]
Still produces a deprecation warning:

```
array->isa      = _CDVJKArrayClass;
```

and

```
dictionary->isa      = _CDVJKDictionaryClass;
```

Any good solution to this?

**Comment by bynelus** [comment]
Same here!

**Comment by themil** [comment]
SOLUTION can be found here :)
https://github.com/IgorFedorchuk/JSONKitWithoutXcode4Warnings

**Comment by SpacyRicochet** [comment]
Those aren't solutions, they just hide away the warnings. Good enough for a quick fix (I'm using it, so thanks), but nothing near a real solution.

**Comment by marcdown** [comment]
Since none of the Pull requests have been accepted I applied the fixes @tknizam suggested as well as used object_setClass(object, Class) to fix @antonysastre's warnings. I also explicitly cast the appropriate format arguments as unsigned long to remove those warnings as well.
Forked repo: https://github.com/creativemess/JSONKit
Podspec: https://gist.github.com/creativemess/5282955/raw/2a52cfd92f112f2a52669420c82c1bb1efd15d2a/JSONKit.podspec

**Comment by luketheobscure** [comment]
@creativemess How do I reference your podspec?

**Comment by marcdown** [comment]
@luketheobscure added the following to your Podfile:

```
pod 'JSONKit', :podspec => 'https://gist.github.com/creativemess/5282955/raw/2a52cfd92f112f2a52669420c82c1bb1efd15d2a/JSONKit.podspec'
```

**Comment by jhonyf** [comment]
Not sure what happened to @marcdown gist, but recreated it to point to his fork. Use this in your podfile and run `pod install`

```
pod 'JSONKit', :podspec => 'https://gist.github.com/jhonyf/7002734/raw/08fd7b28676b97af251b5dd5b375394eedc454f9/gistfile1.rb'
```

**Comment by marcdown** [comment]
@jhonyf I updated my handle - here's the updated link:

```
pod 'JSONKit', :podspec => 'https://gist.github.com/marcdown/5282955/raw/2a52cfd92f112f2a52669420c82c1bb1efd15d2a/JSONKit.podspec'
```

**Comment by PhilTrailerPark** [comment]
Thanks marcdown.  Current JSONKit is still build failing with deprecations but your fork worked great for me.  Thanks for saving me doing it by hand.  Yeah cocoapods!

**Comment by xlarsx** [comment]
Thanks for the update!

**Comment by cesarferreira** [comment]
@marcdown thanks a lot for that line! :)

**Comment by zlc000190** [comment]
i remove the jsonkit
