### ISSUE TITLE
get a warning in Xcode 4.5 dp2

### ISSUE THREAD

**Issue by Whirlwind** [johnezang/JSONKit#84]
I get a waring : JSONKit.m:747:3: Null pointer argument in call to memory copy function

**Comment by catarino** [comment]
I've managed to fix all the other warnings (as you can see in my fork https://github.com/catarino/JSONKit) but the last one standing is precisely the same mentioned here.

**Comment by catarino** [comment]
memcpy(objectsPtr, objects + range.location, range.length \* sizeof(id));

**Comment by Whirlwind** [comment]
I still get the warning. 
:(

**Comment by johnezang** [comment]
This isn't a bug or a problem in JSONKit, it's a problem with `clang`.  It could be argued that this is a bug with `clang`, depending on how big a problem you consider false positives to be.

The static analyzer clearly thinks that the use of `objects` (as an argument to `memcpy`) could potentially be `NULL`.  The analyzer can't _prove_ that it's `NULL`, only that it could possibly be `NULL`, largely because there is no explicit check to make sure `objects` is not `NULL` **_in this method**_.  Those checks _do_ take place in the initialization and resizing functions, though, so it follows that it can't be `NULL` at this particular line.

I might throw in a (yet another) pre-processor `#ifdef` to shut the analyzer up.

**Comment by catarino** [comment]
Fair enough. Thank you. @johnezang :)

**Comment by johnezang** [comment]
Fixed on both `master` and `stable`.

**Comment by catarino** [comment]
Man, you rock. All Good here. :) Thx

**Comment by Whirlwind** [comment]
Good. Thx :)
