### ISSUE TITLE
Failed to parse what seems to be a valid JSON

### ISSUE THREAD

**Issue by ghost** [johnezang/JSONKit#92]
I've been writing my implementation of BSON parser and stumbled upon curious bug
Following JSON trips up many parsers (even `JSONLint` validator), but it seems like it's a valid one from the spec point of view
Also, `NSJSONSerialization` class parses it just fine
Here is the JSON itself:

```
{
    "": {
        "a": "b"
    }, 
    "a": 1, 
}
```

Funny enough, in objective c you can access the first value through `valueForKeyPath:@".a"` and the second one through `valuForKeyPath:@"a"`

**Comment by johnezang** [comment]
The JSON you provided isn't valid JSON, at least according to [RFC 4627](http://tools.ietf.org/html/rfc4627).  You can use the web site http://jsonlint.com/ to verify suspect JSON.

The problem is the second to the last line: `"a": 1,` and specifically with that trailing comma.  For valid JSON, the last item in a JSON dictionary can't have a trailing comma.

**Comment by ghost** [comment]
Ugh my bad, should've slept more.
Sorry
